### ISSUE TITLE
GUILayout

### ISSUE THREAD

**Issue by alomnrk** [inworld-ai/inworld-unity-sdk#42]
Hi! 
Thanks, for great plugin!

Is there any way to turn off GUILayout info about current InworldScene? I mean, of course I can patch code in InworldEditorUtil.cs, but I suppose it'd be better to add functionality for automatically turning it off in scenes that don't have inworld scripts for example.

<img width="678" alt="Screenshot 2023-03-06 at 18 29 10" src="https://user-images.githubusercontent.com/81651669/223155182-22cd8443-a6d5-46dd-a091-4428c9d50e4f.png">

**Comment by Juniverse** [comment]
Hey @alomnrk ,

Thank you for reaching us. Yes all you need to do is turn off `Enable Verbose Log` in `Default Settings`.

![image](https://user-images.githubusercontent.com/68676221/223223013-d1a12ced-d532-44fb-9949-bcbdd6ddceef.png)
