### ISSUE TITLE
Multiple Workspaces

### ISSUE THREAD

**Issue by utkubagdas** [inworld-ai/inworld-unity-sdk#72]
Hey! Can we work with characters from multiple workspaces in a single unity editor? Because the characters in the previous workspace are deleted when you switch to another workspace. Can u help me? Thanks.
(Because 30 is not enough for my project)

**Comment by Juniverse** [comment]
Hello, Thank you for reaching us.

You can switch workspace in runtime, but you need to stop the current session and open the new session. 

You cannot directly enable all the characters from different InworldScenes at the beginning in the Unity scene. You need to turn off the `InworldCharacter` component and its related components that are belonged in the different workspace/scenes.

Also, the logic in Inworld Studio is that workspace contains scenes, and scenes contains characters.  If the characters are deleted in some workspaces, they were not able to be loaded.
